-- DMC initial collection metadata
-- Run after the DMC schema has been created.

insert into public.vehicles
  (number, year, make, model, title, category, vehicle_type, description, sort_order)
values
('01','1924','Chevrolet','','Chevrolet','Automobile archive','CAR','One of the earliest machines in the collection, this Chevrolet connects DMC directly with the formative years of motoring. Its pre-war engineering belongs to a time when automobiles were still developing their fundamental language, making every surviving example a remarkably tangible piece of mechanical history.',1),
('02','1935','Ford Deluxe Phaeton','','Ford Deluxe Phaeton','Automobile archive','CAR','The Deluxe Phaeton captures the confidence of pre-war American automobile design. Its open bodywork, V8 character and generous proportions reflect an era when the automobile was becoming both a practical means of transport and a powerful expression of style.',2),
('03','1936','Austin','','Austin','Automobile archive','CAR','A charming example of British pre-war motoring, the Austin represents an approach centred on compact engineering, practicality and mechanical simplicity. Its character lies in the details and proportions that made British automobiles of the period so distinctive.',3),
('04','1948','Bell Standard','','Bell Standard','Automobile archive','CAR','Emerging in the important post-war period, the Bell Standard represents a generation of automobiles shaped by a world rebuilding itself. Its rarity gives it particular significance within the DMC collection, preserving a lesser-seen chapter of post-war motoring.',4),
('05','1953','Ford Mercury Monterey','','Ford Mercury Monterey','Automobile archive','CAR','The Monterey embodies the optimism and visual drama of 1950s America. Its V8 character, substantial proportions and unmistakable styling belong to an era when automobiles were becoming statements of confidence, freedom and prosperity.',5),
('06','1956','Citroën 2CV','','Citroën 2CV','Automobile archive','CAR','Few cars demonstrate purposeful simplicity like the 2CV. Created around affordable and practical mobility, its unusual engineering, lightweight construction and famously distinctive character made it one of the great examples of French automotive ingenuity.',6),
('07','1957','Dodge Kingsway Custom','','Dodge Kingsway Custom','Automobile archive','CAR','The Dodge Kingsway Custom carries the bold personality of 1950s American design. Chrome, scale and presence were part of its language, making it a fascinating representation of the period belief that a car should be noticed as much as driven.',7),
('08','1959','Hindustan Ambassador Mark I','','Hindustan Ambassador Mark I','Automobile archive','CAR','The Ambassador occupies a unique place in India’s automotive story. The Mark I connects the collection to the beginning of a production lineage that would become deeply woven into Indian life, from government service to family journeys and everyday roads.',8),
('09','1960','Fiat 1100 Select','','Fiat 1100 Select','Automobile archive','CAR','The Fiat 1100 demonstrates how Italian engineering could combine compact practicality with elegant proportions. It represents an important period in European motoring when small cars were becoming sophisticated, versatile and full of personality.',9),
('10','1960','Willys Jeep Station Wagon','','Willys Jeep Station Wagon','Automobile archive','CAR','The Willys Jeep Station Wagon stands at the intersection of utility and everyday motoring. Its rugged engineering and practical body helped establish a template for vehicles that could carry people and equipment while retaining genuine working-vehicle capability.',10),
('11','1961','Chevrolet Impala','','Chevrolet Impala','Automobile archive','CAR','The Impala is pure early-1960s American expression. Large, dramatic and unmistakably confident, it represents an era when automotive styling reflected optimism and imagination as much as engineering.',11),
('12','1964','Fiat 1100 Station Wagon','','Fiat 1100 Station Wagon','Automobile archive','CAR','The Station Wagon version of the Fiat 1100 turns an already practical compact car into a remarkably versatile machine. Its Familiare body style reflects an era when European manufacturers were finding clever ways to make small automobiles serve entire families.',12),
('13','1964','Volkswagen Beetle','','Volkswagen Beetle','Automobile archive','CAR','The Beetle is one of the most recognisable automobiles ever created. Its simple mechanical philosophy, distinctive rear-engine layout and extraordinary global reach turned an unconventional people’s car into an enduring cultural icon.',13),
('14','1965','Austin Mini Cooper','','Austin Mini Cooper','Automobile archive','CAR','The Mini Cooper changed the idea of performance in a small car. Its compact dimensions, front-wheel-drive layout and remarkable agility made it a landmark in automotive packaging, while motorsport success transformed the Mini into a legend.',14),
('15','1968','Fiat 1100R Italian','','Fiat 1100R Italian','Automobile archive','CAR','The 1100R represents the mature evolution of Fiat’s long-running 1100 family. Compact, elegant and practical, it captures the character of everyday Italian motoring during one of the most influential periods in European automobile design.',15),
('16','1969','Fiat 124 LHD Convertible','','Fiat 124 LHD Convertible','Automobile archive','CAR','The Fiat 124 Convertible brings Italian design into the world of open-air touring. Its left-hand-drive configuration and graceful proportions give it a distinctly European character, combining usability with the simple pleasure of an open-top automobile.',16),
('17','1971','Volkswagen Bus Devon Camper','','Volkswagen Bus Devon Camper','Automobile archive','CAR','The Devon Camper turns transportation into a way of life. Built around the idea of travelling rather than simply arriving, it represents the culture of road journeys, exploration and shared experiences that made the Volkswagen Bus an icon far beyond its mechanical specification.',17),
('18','1975','Mercedes-Benz W115','','Mercedes-Benz W115','Automobile archive','CAR','The W115 represents the Mercedes-Benz philosophy of understated engineering. Solid construction, thoughtful mechanical design and long-term durability made these cars respected not for fashion, but for their ability to keep doing their job year after year.',18),
('19','1976','Fiat 126','','Fiat 126','Automobile archive','CAR','Small, economical and unmistakably characterful, the Fiat 126 represents the democratisation of personal mobility in Europe. Its compact engineering demonstrates how much practical transportation could be achieved with very little physical footprint.',19),
('20','1983','Mercedes-Benz W123 — Sedan','','Mercedes-Benz W123 — Sedan','Automobile archive','CAR','The W123 became famous for engineering durability, comfort and build quality. It represents Mercedes-Benz at a point where sophisticated engineering and exceptional longevity came together, creating a car that could remain useful for generations.',20),
('21','1983','Mercedes-Benz W123 — Station Wagon','','Mercedes-Benz W123 — Station Wagon','Automobile archive','CAR','The W123 Station Wagon adds another dimension to the celebrated W123 formula. Its combination of durability, space and understated elegance demonstrates how Mercedes-Benz engineering could serve both family practicality and long-distance motoring.',21),
('22','1993','Mercedes-Benz W124 300D','','Mercedes-Benz W124 300D','Automobile archive','CAR','The W124 300D represents the final generation of classic Mercedes-Benz engineering before modern electronics began transforming the automobile. Its diesel character, durability and restrained design make it a fitting bridge between the analogue classics of the collection and the modern era.',22),
('23','1967','Jawa','','Jawa','Motorcycle archive','BIKE','The Jawa brings Czechoslovak engineering into the collection. Its distinctive mechanical character and strong presence in Indian motorcycle culture make it an important reminder that India’s roads were shaped by machines from many corners of the world.',23),
('24','1962','Rajdoot','','Rajdoot','Motorcycle archive','BIKE','The Rajdoot is part of India’s own two-wheeler heritage. Robust, purposeful and instantly recognisable, it represents a generation for whom motorcycles were practical companions as much as machines, connecting the DMC collection to India’s evolving motorcycling culture.',24),
('25','1967','Lambretta','','Lambretta','Motorcycle archive','BIKE','The Lambretta represents the stylish side of post-war mobility. Compact, elegant and unmistakably Italian, it became an icon of urban transport and scooter culture, proving that practicality and personality did not have to be opposites.',25)
on conflict (number) do update set
  year = excluded.year,
  make = excluded.make,
  model = excluded.model,
  title = excluded.title,
  category = excluded.category,
  vehicle_type = excluded.vehicle_type,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();
